### ISSUE TITLE
Future?

### ISSUE THREAD

**Issue by dumblob** [lieff/lvg#3]
This is a neat endeavor! But how does the future plans look like?

Btw. in the section **Interesting graphics libraries** in readme I couldn't find the most advanced (yet very lightweight) library as of now: [Blend2D](https://github.com/blend2d/blend2d/ ) (quality superior to even Antigrain; [performance close to theoretical limit](https://blend2d.com/performance.html ); ARM support is still alpha/beta though).

**Comment by lieff** [comment]
Hi)
Thanks for the lib) I know that blender uses own lib for paint and interface, but do not look close at it before.
About plans first of all I want to finish avm1 and Web Assembly scripting support. Avm2 is too big, still can be used as subset or big addon, but I`m not sure I can do this alone.
Then I want shader support through https://github.com/lieff/minishadertoy, to easily run shadertoy shaders from script.
Vulkan support also will be nice and not so hard to do. As for other stuff from Future list it's more experimental stuff which can be fun to try, but may never happen.

**Comment by Upliner** [comment]
> I know that blender uses own lib for paint and interface, but do not look close at it before.

It seems that Blend2D has nothing to do with Blender.

**Comment by lieff** [comment]
Right, and as I can see currently Blender do not use any external GUI lib. I seem to have mix-up it with something else.

**Comment by dumblob** [comment]
> About plans first of all I want to finish avm1 and Web Assembly scripting support. Avm2 is too big, still can be used as subset or big addon, but I`m not sure I can do this alone.
> Then I want shader support through https://github.com/lieff/minishadertoy, to easily run shadertoy shaders from script.
> Vulkan support also will be nice and not so hard to do. As for other stuff from Future list it's more experimental stuff which can be fun to try, but may never happen.

Those are big plans. That's actually great! I'm looking forward to this project thriving!
